### ISSUE TITLE
Bug report for 4.1 AT beta. 

### ISSUE THREAD

**Issue by KillerRamer** [Lycaonj/AdvancedThaumaturgy#13]
On the second page for the Mercurial wand core, Two lines beginning with \n\n. "\n\n This will make node collecting," and "\n\n The creation process.."

particles from breaking the fertilizer having some odd imagine and words on them.

Ethereal jars no longer show in creative. 

Cannot craft the mercurial wand in the arcane workbench

Also a crash involving the new foci void cage-http://pastebin.com/aFu9hHDe 

Breaking an Ethereal jar that is empty yields the jar, and a normal jar in return.

**Comment by MagisterXero** [comment]
I'd like to further add to this bug. "Breaking an Ethereal jar that is empty yields the jar, and a normal jar in return."

Breaking an Ethereal Jar which CONTAINS essentia already, also yields the jar, plus a normal jar with the same amount. (Warded jars with 256 essentia are possible because of this bug. The liquids render way up above the jars)

**Comment by Lycaonj** [comment]
Can I get any details on the Void Focus crash?

Did you have an entity in it?  What block did you right click?  What side of the block?  Were you holding shift?  Did you have enough vis?

**Comment by Lycaonj** [comment]
Fixed all the other bugs in build 22.

**Comment by LemmaEOF** [comment]
He'll need to update to the Thaumcraft 4.1 API for everything to work properly. I tried AT with TC4.1, and practically anything AT related will result in a fatal crash.

**Comment by Lycaonj** [comment]
Appeared to have fixed the void focus crash as well.  -- Build 23
