### ISSUE TITLE
Ethereal Jars

### ISSUE THREAD

**Issue by SpitefulFox** [Lycaonj/AdvancedThaumaturgy#3]
Breaking an empty ethereal jar drops an invisible ethereal jar that won't stack.

Also, the research is branching off of Node In a Jar instead of the Essentia Distillation.  Not sure if intentional.

**Comment by Lycaonj** [comment]
Fixed the first issue.  The second issue is semi intended.  Having stacking jars would mean coding two entirely separate classes for the jar :\  Third is fixed in b17pr2 as well.

Next time, please separate distinct problems into their own issues so that they can be commented on and closed individually :)
