### ISSUE TITLE
Is the wand supposed to hold 1000 of the primal aspects?

### ISSUE THREAD

**Issue by Feartheninja23** [Lycaonj/AdvancedThaumaturgy#47]
I upgraded the wand with all of the upgrade crystals, and it now hold 1000 of the aspects, just like the thaumic tinkerer KAMI ichorium wand. I urge you to fix this bug, or make the recipes even harder because I have achieved a super end game wand at no where near the cost or infusion instability of KAMI.

**Comment by Lycaonj** [comment]
It's intentional.  While the balance of AT -is- thrown off a bit by the sliding mechanic, is it really that game-breaking to obtain a powerful wand an hour before you dress yourself up im KAMI gear?  Unfortunately, I'm not sure I can do a sliding difficulty on the actual Mercurial Wand recipe, but I will look into it.  At the moment, I am without a keyboard (am currently on a tablet) so work on AT is sadly on hold until I can manage to come up with enough money to get a backlit keyboard (I am visually impaired, a cheap $10 keyboard won't work).

**Comment by Lycaonj** [comment]
What I might do is keep the wand at a base 500 bis and selectively add in upgrade crystals to increase the capacity based on what other wand cores are available.  This might prove a challenge though, since I don't think you can change a core's vis capacity.  Wand core vis capacity is set at mod initialization time.

**Comment by Feartheninja23** [comment]
I suppose that there is not much you can do to change the recipe, but making the instability higher, and maybe requiring more complex aspects would help balance it. Right now, I have a wand that is basically better than the ichor wand, because it gives a higher vis discount, regens 15% of it's aspects, and a whole lot of bonuses that the ichor wand doesn't give. And I got it all for less nether stars. The aspects aren't too demanding either because all you really need for the actual wand is 4 stacks of fire shards and greatwood logs. Maybe making the wan upgrades more difficult to obtain would help balance it out a little.

**Comment by Lycaonj** [comment]
. -- Sorry this reply is months behind.  Health has been terrible and I am just now getting back into things.  If this is still an issue in 1.7.10 (after the build for it is posted) feel free to reopen.
